FROM python:3.13-slim AS poetry-builder
WORKDIR /app

ENV POETRY_VIRTUALENVS_IN_PROJECT=true

COPY --chown=1002:1002 pyproject.toml poetry.lock ./

RUN pip install --upgrade pip && \
    pip install --no-cache-dir poetry && \
    poetry install --without dev --no-root

FROM python:3.13-slim AS runtime
WORKDIR /app

RUN apt-get update && \
    apt-get install -y curl ffmpeg git git-lfs ca-certificates && \
    rm -rf /var/lib/apt/lists/* && \
    useradd -u 1002 -m appuser && \
    chown 1002:1002 /app

USER appuser
RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
    . $HOME/.local/bin/env && \
    git lfs install && \
    # TODO: add --depth 1 --shallow-submodules once we have accommodated our work for the
    # latest VTC 2 and VTC 2 repository has finally stabilised
    git clone --recurse-submodules https://github.com/LAAC-LSCP/VTC.git && \
    cd VTC && \
    # Remove the below 2 lines when above change is made
    git checkout efb6e4400bd345048740c05136dc79529daf82ad && \
    git submodule update --init --recursive && \
    uv sync
USER root

ENV VIRTUAL_ENV=/app/.venv \
    PATH="/app/.venv/bin:$PATH:/root/.local/bin"

COPY --chown=1002:1002 --from=poetry-builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}

ENTRYPOINT ["python"]
CMD ["-m", "src.cli"]
