FROM python:3.13-slim AS repo-builder
WORKDIR /app
RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/* && \
    git clone --depth 1 --recurse-submodules --shallow-submodules https://github.com/MarvinLvn/voice_type_classifier.git

FROM continuumio/miniconda3:latest AS conda-builder
WORKDIR /app
COPY --from=repo-builder /app/voice_type_classifier /app/voice_type_classifier
RUN cd ./voice_type_classifier && \
    conda env create -f vtc.yml

FROM python:3.13-slim AS poetry-builder
WORKDIR /app

COPY --chown=1002:1002 pyproject.toml poetry.lock ./

ENV POETRY_VIRTUALENVS_IN_PROJECT=true

RUN pip install --upgrade pip && \
    pip install --no-cache-dir poetry && \
    poetry install --without dev --no-root

FROM python:3.13-slim AS runtime
WORKDIR /app

RUN apt-get update && \
    apt-get install -y sox && \
    rm -rf /var/lib/apt/lists/*

ENV VIRTUAL_ENV=/app/.venv \
    PATH="/app/.venv/bin:$PATH"

COPY --chown=1002:1002 --from=repo-builder /app/voice_type_classifier /app/voice_type_classifier
COPY --chown=1002:1002 --from=poetry-builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}
COPY --chown=1002:1002 --from=conda-builder /opt/conda /opt/conda

ENTRYPOINT ["python"]
CMD ["-m", "src.cli"]
