FROM python:3.13-slim AS poetry-builder
WORKDIR /app

COPY --chown=1002:1002 pyproject.toml poetry.lock ./

ENV POETRY_VIRTUALENVS_IN_PROJECT=true

RUN pip install --upgrade pip && \
    pip install --no-cache-dir poetry && \
    poetry install --no-root

FROM python:3.13-slim AS runtime
WORKDIR /app

ENV VIRTUAL_ENV=/app/.venv \
    PATH="/app/.venv/bin:$PATH"

COPY --chown=1002:1002 --from=poetry-builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}

ENTRYPOINT ["python"]
CMD ["-m", "src.cli"]
